dist: focal
language: python

branches:
  only:
    - main

python:
  - '3.9'
  - '3.12'

services:
  - docker

addons:
  apt:
    packages:
      - poppler-utils

before_install:
  - pip install --upgrade pip setuptools packaging
  - if ! [ -f ./src/GRCh37.tar.gz ]; then wget --connect-timeout=10 --tries=20 ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz -P ./src/; fi

install:
  - pip install .[tests]

cache:
  directories:
    - $TRAVIS_BUILD_DIR/src/

before_script:
  - python3 install_genome.py $TRAVIS_BUILD_DIR/src/

script: 
  - pytest tests
  - python3 test.py

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "main" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.12" ]; then
      echo "Starting Docker deployment to GHCR for alexandrovlab..."

      VERSION_TAG=$(grep "VERSION = " setup.py | cut -d'"' -f2)

      # Get the repository name and convert it to lowercase
      REPO_NAME=$(basename $TRAVIS_REPO_SLUG | tr '[:upper:]' '[:lower:]')
      IMAGE_NAME="ghcr.io/alexandrovlab/$REPO_NAME"

      echo "Checking if $IMAGE_NAME:$VERSION_TAG already exists on GHCR..."
      echo "$GHCR_PASSWORD" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin

      if docker manifest inspect $IMAGE_NAME:$VERSION_TAG > /dev/null 2>&1; then
        echo "Tag $IMAGE_NAME:$VERSION_TAG already exists. Skipping Docker push."
      else
        echo "Building version: $VERSION_TAG for image: $IMAGE_NAME"

        docker build \
          --build-arg COMMIT_SHA=$TRAVIS_COMMIT \
          -t $IMAGE_NAME:$VERSION_TAG \
          -t $IMAGE_NAME:latest .

        docker push $IMAGE_NAME:$VERSION_TAG
        docker push $IMAGE_NAME:latest

        echo "Docker deployment to GHCR successful"
      fi
    else
      echo "Skipping Docker deployment"
    fi
