dist: xenial
language: python

python:
  - '3.8'

cache:
  directories:
    - $TRAVIS_BUILD_DIR/src/
  branch:
    - master

before_install:
  if ! [ -f ./src/GRCh37.tar.gz ]; then
    wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz -P ./src/;
  fi

install:
  - pip install .[tests]

before_script:
  - python3 install_genome.py $TRAVIS_BUILD_DIR/src/

script: 
  # run unit tests
  - pytest tests
  # run integration tests
  - python3 test.py
