dist: xenial
language: python

vm:
  size: large

python:
  - '3.8'

before_install:
  if ! [ -f ./src/GRCh37.tar.gz ]; then
    wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz -P ./src/;
  fi

install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda install -c conda-forge -y mscorefonts
  - python -m pip install .

cache:
  directories:
    - $TRAVIS_BUILD_DIR/src/

before_script:
  - python3 install_genome.py $TRAVIS_BUILD_DIR/src/
  - conda install -c conda-forge -y mscorefonts

script: python3 test.py
